### ISSUE TITLE
"Liberate the Kingdom of Nubia" decision for Ethiopia Should Probably Give Nubian as an Accepted Culture

### ISSUE THREAD

**Issue by TovarFriedman** [Capitanloco6/Divergences-HPM#16]
It effectively just gives you a cheap cb to take the land. The thing is, flavour-wise, the purpose is to free minorities. As such, it doesn't really make sense that those minorities are then discriminated against (because they are not accepted). But this is fairly subjective.

**Comment by TovarFriedman** [comment]
Nevermind. I did it and saw that there was a decision to integrate stuff once you had taken it. My bad.

**Comment by TovarFriedman** [comment]
So, when I wrote this, I didn't realize there was a decision to get the people there as an accepted culture. I do feel that it might be a good idea to give Ethiopia cores on the land as well though, assuming that there is not also an event or decision for that which I have not yet seen.

**Comment by Lys0gen** [comment]
You get the "core integration" modifier on the provinces which eventually should turn them into actual cores for you.
