### ISSUE TITLE
(HPM series bug) Adding poor_everyday_needs to province modifiers can break the economy

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [Capitanloco6/Divergences-HPM#28]
@Capitanloco6 As reported here and other places: https://www.reddit.com/r/victoria2/comments/niy61g/gamebreaking_bug_with_all_popular_mods/
Adding pop needs modifiers to province modifiers can stop all demand for goods. Currently worker_union, foreign_smugglers, fascist_welfare and foreign_trading_post are affected.

**Comment by Capitanloco6** [comment]
Duly noted! I've disabled these effects for now in said event modifiers.

**Comment by Outta-my-way-burrocrat** [comment]
foreign_smugglers and foreign_trading_post are only affected if they are applied as province modifiers instead of national modifiers like vanilla vic2.
