### ISSUE TITLE
Taiwan Province Names

### ISSUE THREAD

**Issue by Sonderkugel** [Capitanloco6/Divergences-HPM#3]
Some of the province names on Taiwan are mixed up or wrong. Taipei (2681) is correct but Taibei (1485) is just another name for Taipei and should be called Tainan while what's currently Tainan (2562) should be called Taitung. The names from the Japanese Formosa event are also wrong: Taipei (2681) should be renamed Taihoku, Taitung/Tainan (2562) should be renamed Taito, Penghu (2406) should be renamed Hoko, and Tainan/Taibei (1485) should remain the same. Also the Japanese name for the region "Takasago" is kind of archaic and by this time was just used by the Japanese for the Taiwanese aboriginals, so the region name should be Taiwan.

**Comment by Capitanloco6** [comment]
Implemented in the latest patch, thanks for the suggestion!
