### ISSUE TITLE
Map bugs

### ISSUE THREAD

**Issue by Outta-my-way-burrocrat** [Capitanloco6/Divergences-HPM#30]
[pimppin](https://www.moddb.com/members/pimppin) 57mins ago	https://www.moddb.com/mods/divergences-of-darkness/downloads/divergences-of-darkness-mesoameriga-patch

"The province of Tuxtla located in the state of Tabasco appears to be bugged seeing as you can build a dockyard there and produce vessels which wouldn't be an issue if the state it self wouldn't be landlocked causing any ship built there to be completely immobile."

New Zealand is offset north and most of its naval bases are bugged because of it.

PROV2187 and PROV3448 are named Quetzaltenango.

Event 334324 gives Kirikiriroa to Japan.

**Comment by Outta-my-way-burrocrat** [comment]
PROV2187 and PROV3448 are named Quetzaltenango.

**Comment by Outta-my-way-burrocrat** [comment]
Event 334324 gives Kirikiriroa to Japan

**Comment by Capitanloco6** [comment]
Apologies for the late replies - I think it's better if you join our section of the modding discord and manage things there. Ping me (majormajor) and I'll give you the roles you need for the dev section https://discord.gg/DmyDdDxH
